export const locators = {
    SignInbaseurl: 'https://africhange-business-web-test-af736fe5bea2.herokuapp.com/',
    LoginButton: '',
    SignUpbaseurl: 'https://africhange-business-web-stagin-91ad959e2166.herokuapp.com/request-access',
    FirstName: '//*[@id="First Nameid6805"]',
    LastName: "//input[@id='Last Nameid2046']",
    MiddleName: "//input[@id='Middle Nameid2604']",
    Email: "//input[@id='Emailid2128']",
    PhoneNumberSelector: "//nz-select-item[@title='+234']",
    PhoneNumber: "//input[@id='Phone Numberid3750']",
    BusinessName: "//input[@id='Business Nameid1102']",
    AmountSelector: "//nz-select-top-control[@class='ant-select-selector ng-tns-c146563758-31']//input[@class='ant-select-selection-search-input ng-pristine ng-valid ng-touched']",
    TransactionValue: "//nz-option-item[@title='₦10million to ₦90million']//div[1]",
    StreetNumber: "//input[@id='Street numberid5913']",
    Address: "//input[@id='Addressid7842']",
    City: "//input[@id='Cityid3175']",
    State: "//input[@id='Stateid245']",
    PostalCode: "//input[@id='Postal Codeid9777']",
    TellUsAboutYourself: "//textarea[@id='About the businessid8119']",
    TermsAndcondition: "//input[@type='checkbox']",
    RequestButton: "//button[@id='btn-id-88575']",
    UserEmail: "name@example.com",
    EmailAddress: "johnsonoketa+90@africhange.com",
    PasswordSpace: "Your password",
    Password: "P@ssword1",
    WrongEmail: "johnsonoketa2@africhange.com",
    LogOutModal: 'svg[data-icon="menu-fold"]',
    dashboardTitle: "h4.dashboard-header-title",
    NigeriaWallet: 'img[src="assets/svgs/nigeria-wallet-icon.svg"]',
    CanadaWallet: 'img[alt="Country Icon"]',
  };
  